name: Test

on:
  workflow_dispatch:

  push:
    branches:
      - main
  
  pull_request:

env:
  NODE_VERSION: "20.11.0"

jobs:
  build:
    runs-on: ubuntu-latest
    # For later use
    # strategy:
    #   matrix:
    #     node: [ 18, 20 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Print Node Version
        run: node --version && npm --version

      - name: Install Dependencies
        run: npm ci

      - name: Run test
        run: npm test