name: Test

on:
  workflow_dispatch:

  push:
    branches:
      - main
  
  pull_request:

env:
  NODE_VERSION: "20.11.1"
  PNPM_VERSION: "8.15.1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run test
        run: pnpm test