name: Test

on:
  workflow_dispatch:

  push:
    branches:
      - main
  
  pull_request:

env:
  NODE_VERSION: "20.11.0"

jobs:
  build:
    runs-on: ubuntu-latest
    # For later use
    # strategy:
    #   matrix:
    #     node: [ 18, 20 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false
      
      # - name: Print Node Version
      #   run: node --version && npm --version

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Run test
        run: pnpm test