name: Test

on:
  workflow_dispatch:

  push:
    branches:
      - main
  
  pull_request:

env:
  NODE_VERSION: "20.11.1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install Dependencies
        run: npm ci --include=peer

      - name: Run test
        run: npm test